### ISSUE TITLE
Spellcheck and documentation for DEVICE_ID

### ISSUE THREAD

**Issue by tueddy** [plenproject/plen__firmware_for_Arduino#11]
Hi,
small spellcheck error RANDOM_DEVCIE_IN should be RANDOM_DEVICE_IN
Can you also document how DEVICE_ID is enumerated? More than one Plen2 in the room?

**Comment by plenproject** [comment]
Thank you for reporting the issue.
We will fix it at firmware version 1.3 that will be adding other functions.

We haven't understood the word "DEVICE_ID" accurately.
Why the information is needed because do you want to connect PLEN2 with BLE?
