### ISSUE TITLE
Make sourcecode documentation on english available

### ISSUE THREAD

**Issue by tueddy** [plenproject/plen__firmware_for_Arduino#9]
Hello Plen2 programmer,
please make sourcecode documentation available also for english. Japanese is a bit cryptic here.
Some comments are very important to understand the code.
Suggestion: Maybe as a start translate it via Google translate. Dual language is OK.

Thanks & best regards from germany
Dirk

**Comment by plenproject** [comment]
Hi, tueddy.

Yes, we have understood the importance of documentation on english.
We have started documents translation in english, but we will spend a lot of time.

Sorry we cannot give everyone english documents currently. Please wait for a follow-up.

**Comment by tueddy** [comment]
Hello,

thanks for the feedback! Looking forward,
best regards
Dirk
